name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    name: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            export BACKEND_URL=${{ secrets.BACKEND_URL }}
            export FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            
            echo "Stopping any running bot instance..."
            pkill -f "node bot.js" || true
            
            rm -rf telegram-bot
            git clone https://github.com/saygoodluck/telegram-bot.git
            cd telegram-bot
            npm i
            
            # Запуск бота в фоновом режиме с полным отсоединением
            nohup setsid node bot.js > bot.log 2>&1 &
            
            # Ждем несколько секунд, чтобы бот успел запуститься
            sleep 5

            # Проверяем, запущен ли бот
            if pgrep -f "node bot.js" > /dev/null; then
              echo "Bot is running."
            else
              echo "Bot failed to start."
              exit 1
            fi
