name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    name: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            export BACKEND_URL=${{ secrets.BACKEND_URL }}
            export FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            rm -rf telegram-bot
            git clone https://github.com/saygoodluck/telegram-bot.git
            cd /root/telegram-bot
            npm i
            node bot.js